plugins:
    - Pageon\Stitcher\FbEventsPlugin

environment: live

fb.events.access.token: 2308023792756516|bF39S1ObF4NGZnMMw6C3wEZRq_E
fb.events.pages:
    - 52796158499
    - 281308288730977
    - 16453782010
    - 934239246594888
    - 217246480168

fb.events.days.past: 7
fb.events.days.future: 7
fb.events.file: data/_fb_events.yml

directories:
    src: ./src
    public: ./public
    cache: ./.cache
    template: ./src/template

meta:
    viewport: width=device-width, initial-scale=1
    chartset: utf-8
    description: Stein's Nightlab

# Minify CSS and JavaScript
minify: false

engines:
    template: smarty
    image: gd
    optimizer: true
    minifier: true

cache:
    images: false
    cdn: false
